#services:
#  app:
#    image: eslamelbadry/socailcrm-app:${APP_VERSION}
#    build: {}
#
#  node:
#    image: eslamelbadry/socailcrm-node:${NODE_VERSION}
#  reverb:
#    image: eslamelbadry/socailcrm-reverb:${REVERB_VERSION}
#
#  horizon:
#    image: eslamelbadry/socailcrm-horizon:${HORIZON_VERSION}
#
#  nginx:
#    depends_on:
#      app:
#        condition: service_started
#        required: true
#    volumes:
#      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
#      - ./letsencrypt:/etc/letsencrypt:ro
#      - ./letsencrypt/www:/var/www/certbot:ro
#
#  certbot:
#    image: certbot/certbot:latest
#    container_name: laravel-certbot
#    depends_on:
#      - nginx
#    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./letsencrypt/www:/var/www/certbot
#
#volumes:
#  letsencrypt:
